server:
  port: 8080

spring:
  application:
    name: task-app-default
  datasource:
    url: jdbc:mysql://mysql-db:3306/taskdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
